package com.portfolio.manager.presentation.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

import com.portfolio.manager.domain.model.SortOption

import java.util.Locale

enum class AppLanguage(val code: String) {
    ENGLISH("en"),
    KOREAN("ko");

    companion object {
        fun fromCode(code: String?): AppLanguage? = entries.find { it.code == code }

        fun fromLocale(locale: Locale): AppLanguage =
            if (locale.language == KOREAN.code) KOREAN else ENGLISH
    }
}

data class AppStrings(
    val settings: String,
    val language: String,
    val english: String,
    val korean: String,
    val close: String,
    val cancel: String,
    val apply: String,
    val save: String,
    val create: String,
    val update: String,
    val delete: String,
    val edit: String,
    val retry: String,
    val back: String,
    val refresh: String,
    val reset: String,
    val loading: String,
    val folio: String,
    val fireCalculator: String,
    val household: String,
    val householdSharing: String,
    val manageAccounts: String,
    val add: String,
    val rebalance: String,
    val addToPortfolio: String,
    val addStockHolding: String,
    val addCashSavings: String,
    val failedToLoadPrices: String,
    val deleteHolding: String,
    val deleteCash: String,
    val account: String,
    val accounts: String,
    val all: String,
    val selectAccount: String,
    val filterAccounts: String,
    val filterAccountsDescription: String,
    val selectAll: String,
    val needsRebalancing: String,
    val noAccountsYet: String,
    val tapToCreateAccount: String,
    val addAccount: String,
    val newAccount: String,
    val editAccount: String,
    val accountName: String,
    val enterAccountName: String,
    val moveUp: String,
    val moveDown: String,
    val goBack: String,
    val myHoldings: String,
    val cash: String,
    val allocation: String,
    val showLess: String,
    val expand: String,
    val collapse: String,
    val sort: String,
    val sparklinePeriod: String,
    val gainLoss: String,
    val today: String,
    val todayPercent: String,
    val annualDividends: String,
    val portfolio: String,
    val mdd: String,
    val volatility: String,
    val sharpe: String,
    val best: String,
    val worst: String,
    val total: String,
    val dividend: String,
    val weight: String,
    val perAccount: String,
    val trendingUp: String,
    val trendingDown: String,
    val yield: String,
    val addHolding: String,
    val editHolding: String,
    val symbol: String,
    val symbolPlaceholder: String,
    val quantity: String,
    val quantityPlaceholder: String,
    val averagePrice: String,
    val averagePricePlaceholder: String,
    val currency: String,
    val addCash: String,
    val editCash: String,
    val name: String,
    val cashNamePlaceholder: String,
    val value: String,
    val valuePlaceholder: String,
    val annualYield: String,
    val annualYieldPlaceholder: String,
    val totalPortfolio: String,
    val annualReturn: String,
    val annualInflation: String,
    val realReturn: String,
    val sustainableSpending: String,
    val sustainableSpendingDescription: String,
    val monthly: String,
    val annually: String,
    val realReturnWarning: String,
    val fireTarget: String,
    val targetMonthlySpending: String,
    val requiredPortfolio: String,
    val progress: String,
    val remaining: String,
    val notAvailableRealReturn: String,
    val householdCode: String,
    val householdCodeInstructions: String,
    val leaveHousehold: String,
    val displayName: String,
    val createHousehold: String,
    val joinHousehold: String,
    val householdCodePlaceholder: String,
    val joinWithCode: String,
    val rebalancePortfolio: String,
    val toleranceBand: String,
    val emptyPerShareRule: String,
    val setTargetPercentages: String,
    val recommendations: String,
    val buy: String,
    val sell: String,
    val ok: String,
    val noChartData: String,
    val statistics: String,
    val tapChartDetails: String,
    val high: String,
    val low: String,
    val average: String,
    val periodReturn: String,
    val items: (Int) -> String,
    val allWithCount: (Int) -> String,
    val filteredAccounts: (Int, Int, Int) -> String,
    val moreItems: (Int) -> String,
    val sharesAt: (Int, String) -> String,
    val deleteHoldingMessage: (String, Int) -> String,
    val deleteCashMessage: (String) -> String,
    val editInAccount: (String) -> String,
    val deleteFromAccount: (String) -> String,
    val targetMonthlySpendingLabel: (Boolean) -> String,
    val recommendationShares: (String, String, Int, Double) -> String,
    val sortOptionLabel: (SortOption) -> String
)

val EnglishAppStrings = AppStrings(
    settings = "Settings",
    language = "Language",
    english = "English",
    korean = "Korean",
    close = "Close",
    cancel = "Cancel",
    apply = "Apply",
    save = "Save",
    create = "Create",
    update = "Update",
    delete = "Delete",
    edit = "Edit",
    retry = "Retry",
    back = "Back",
    refresh = "Refresh",
    reset = "Reset",
    loading = "Loading...",
    folio = "Folio",
    fireCalculator = "FIRE Calculator",
    household = "Household",
    householdSharing = "Household sharing",
    manageAccounts = "Manage Accounts",
    add = "Add",
    rebalance = "Rebalance",
    addToPortfolio = "Add to Portfolio",
    addStockHolding = "Add Stock Holding",
    addCashSavings = "Add Cash / Savings",
    failedToLoadPrices = "Failed to load prices",
    deleteHolding = "Delete Holding",
    deleteCash = "Delete Cash",
    account = "Account",
    accounts = "Accounts",
    all = "All",
    selectAccount = "Select account",
    filterAccounts = "Filter Accounts",
    filterAccountsDescription = "Select accounts to include in the aggregated view",
    selectAll = "Select All",
    needsRebalancing = "Needs rebalancing",
    noAccountsYet = "No accounts yet",
    tapToCreateAccount = "Tap + to create your first account",
    addAccount = "Add Account",
    newAccount = "New Account",
    editAccount = "Edit Account",
    accountName = "Account Name",
    enterAccountName = "Enter a name for your new account",
    moveUp = "Move up",
    moveDown = "Move down",
    goBack = "Go Back",
    myHoldings = "My Holdings",
    cash = "Cash",
    allocation = "Allocation",
    showLess = "Show less",
    expand = "Expand",
    collapse = "Collapse",
    sort = "Sort",
    sparklinePeriod = "Sparkline Period",
    gainLoss = "Gain/Loss",
    today = "Today",
    todayPercent = "Today %",
    annualDividends = "Annual Dividends",
    portfolio = "Portfolio",
    mdd = "MDD",
    volatility = "Vol",
    sharpe = "Sharpe",
    best = "Best",
    worst = "Worst",
    total = "Total",
    dividend = "Div",
    weight = "Weight",
    perAccount = "Per Account",
    trendingUp = "Trending up",
    trendingDown = "Trending down",
    yield = "Yield",
    addHolding = "Add Holding",
    editHolding = "Edit Holding",
    symbol = "Symbol",
    symbolPlaceholder = "e.g., AAPL or 005930",
    quantity = "Quantity",
    quantityPlaceholder = "e.g., 10",
    averagePrice = "Average Price",
    averagePricePlaceholder = "e.g., 150.00",
    currency = "Currency",
    addCash = "Add Cash",
    editCash = "Edit Cash",
    name = "Name",
    cashNamePlaceholder = "e.g., Emergency Fund, CD",
    value = "Value",
    valuePlaceholder = "e.g., 10000",
    annualYield = "Annual Yield (%)",
    annualYieldPlaceholder = "e.g., 4.5",
    totalPortfolio = "Total Portfolio",
    annualReturn = "Annual Return (%)",
    annualInflation = "Annual Inflation (%)",
    realReturn = "Real Return",
    sustainableSpending = "Sustainable Spending",
    sustainableSpendingDescription = "Based on your portfolio and expected real return, you can sustainably spend:",
    monthly = "Monthly",
    annually = "Annually",
    realReturnWarning = "With current settings (real return <= 0%), sustainable spending is zero to maintain portfolio value.",
    fireTarget = "FIRE Target",
    targetMonthlySpending = "Target Monthly Spending",
    requiredPortfolio = "Required Portfolio",
    progress = "Progress",
    remaining = "Remaining",
    notAvailableRealReturn = "N/A (real return <= 0%)",
    householdCode = "Your household code",
    householdCodeInstructions = "Share this code with your partner. They enter it under \"Join a household\".",
    leaveHousehold = "Leave household",
    displayName = "Your display name",
    createHousehold = "Create a household",
    joinHousehold = "Join a household",
    householdCodePlaceholder = "Household code (e.g. ABCD-2345)",
    joinWithCode = "Join with code",
    rebalancePortfolio = "Rebalance Portfolio",
    toleranceBand = "Tolerance band",
    emptyPerShareRule = "Empty = per-share rule",
    setTargetPercentages = "Set Target Percentages",
    recommendations = "Recommendations",
    buy = "Buy",
    sell = "Sell",
    ok = "OK",
    noChartData = "No chart data available",
    statistics = "Statistics",
    tapChartDetails = "Tap on chart to see price details",
    high = "High",
    low = "Low",
    average = "Average",
    periodReturn = "Period Return",
    items = { count -> "$count items" },
    allWithCount = { count -> "All ($count)" },
    filteredAccounts = { selected, total, count -> "$selected of $total ($count)" },
    moreItems = { count -> "+$count more" },
    sharesAt = { quantity, price -> "$quantity shares @ $price" },
    deleteHoldingMessage = { symbol, quantity -> "Are you sure you want to delete $symbol ($quantity shares)?" },
    deleteCashMessage = { name -> "Are you sure you want to delete \"$name\"?" },
    editInAccount = { accountName -> "Edit in $accountName" },
    deleteFromAccount = { accountName -> "Delete from $accountName" },
    targetMonthlySpendingLabel = { showInKrw -> "Target Monthly Spending (${if (showInKrw) "KRW" else "USD"})" },
    recommendationShares = { current, target, currentShares, idealShares ->
        "$current% -> $target% ($currentShares -> ${"%.2f".format(idealShares)} shares)"
    },
    sortOptionLabel = { option -> option.label }
)

val KoreanAppStrings = AppStrings(
    settings = "설정",
    language = "언어",
    english = "English",
    korean = "한국어",
    close = "닫기",
    cancel = "취소",
    apply = "적용",
    save = "저장",
    create = "생성",
    update = "수정",
    delete = "삭제",
    edit = "편집",
    retry = "다시 시도",
    back = "뒤로",
    refresh = "새로고침",
    reset = "초기화",
    loading = "불러오는 중...",
    folio = "Folio",
    fireCalculator = "FIRE 계산기",
    household = "가계",
    householdSharing = "가계 공유",
    manageAccounts = "계정 관리",
    add = "추가",
    rebalance = "리밸런싱",
    addToPortfolio = "포트폴리오에 추가",
    addStockHolding = "주식 보유 추가",
    addCashSavings = "현금/저축 추가",
    failedToLoadPrices = "가격을 불러오지 못했습니다",
    deleteHolding = "보유 종목 삭제",
    deleteCash = "현금 항목 삭제",
    account = "계정",
    accounts = "계정",
    all = "전체",
    selectAccount = "계정 선택",
    filterAccounts = "계정 필터",
    filterAccountsDescription = "통합 보기에서 포함할 계정을 선택하세요",
    selectAll = "전체 선택",
    needsRebalancing = "리밸런싱 필요",
    noAccountsYet = "아직 계정이 없습니다",
    tapToCreateAccount = "+ 버튼을 눌러 첫 계정을 만드세요",
    addAccount = "계정 추가",
    newAccount = "새 계정",
    editAccount = "계정 편집",
    accountName = "계정 이름",
    enterAccountName = "새 계정 이름을 입력하세요",
    moveUp = "위로 이동",
    moveDown = "아래로 이동",
    goBack = "돌아가기",
    myHoldings = "내 보유 종목",
    cash = "현금",
    allocation = "자산 배분",
    showLess = "접기",
    expand = "펼치기",
    collapse = "접기",
    sort = "정렬",
    sparklinePeriod = "차트 기간",
    gainLoss = "손익",
    today = "오늘",
    todayPercent = "오늘 %",
    annualDividends = "연간 배당/이자",
    portfolio = "포트폴리오",
    mdd = "MDD",
    volatility = "변동성",
    sharpe = "샤프",
    best = "최고",
    worst = "최저",
    total = "총액",
    dividend = "배당",
    weight = "비중",
    perAccount = "계정별",
    trendingUp = "상승",
    trendingDown = "하락",
    yield = "수익률",
    addHolding = "보유 종목 추가",
    editHolding = "보유 종목 편집",
    symbol = "종목 코드",
    symbolPlaceholder = "예: AAPL 또는 005930",
    quantity = "수량",
    quantityPlaceholder = "예: 10",
    averagePrice = "평균 매수가",
    averagePricePlaceholder = "예: 150.00",
    currency = "통화",
    addCash = "현금 추가",
    editCash = "현금 편집",
    name = "이름",
    cashNamePlaceholder = "예: 비상금, 예금",
    value = "금액",
    valuePlaceholder = "예: 10000",
    annualYield = "연 이율 (%)",
    annualYieldPlaceholder = "예: 4.5",
    totalPortfolio = "전체 포트폴리오",
    annualReturn = "연 수익률 (%)",
    annualInflation = "연 물가상승률 (%)",
    realReturn = "실질 수익률",
    sustainableSpending = "지속 가능 지출",
    sustainableSpendingDescription = "현재 포트폴리오와 예상 실질 수익률 기준으로 지속 가능한 지출액입니다:",
    monthly = "월간",
    annually = "연간",
    realReturnWarning = "현재 설정에서는 실질 수익률이 0% 이하라 포트폴리오 가치를 유지하려면 지속 가능 지출이 0입니다.",
    fireTarget = "FIRE 목표",
    targetMonthlySpending = "목표 월 지출",
    requiredPortfolio = "필요 포트폴리오",
    progress = "진행률",
    remaining = "남은 금액",
    notAvailableRealReturn = "해당 없음 (실질 수익률 <= 0%)",
    householdCode = "내 가계 코드",
    householdCodeInstructions = "이 코드를 파트너에게 공유하세요. 파트너는 \"가계 참여\"에서 입력하면 됩니다.",
    leaveHousehold = "가계 나가기",
    displayName = "표시 이름",
    createHousehold = "가계 만들기",
    joinHousehold = "가계 참여",
    householdCodePlaceholder = "가계 코드 (예: ABCD-2345)",
    joinWithCode = "코드로 참여",
    rebalancePortfolio = "포트폴리오 리밸런싱",
    toleranceBand = "허용 밴드",
    emptyPerShareRule = "비워두면 주당 규칙 적용",
    setTargetPercentages = "목표 비중 설정",
    recommendations = "추천 조정",
    buy = "매수",
    sell = "매도",
    ok = "확인",
    noChartData = "차트 데이터가 없습니다",
    statistics = "통계",
    tapChartDetails = "차트를 눌러 가격 상세를 확인하세요",
    high = "고점",
    low = "저점",
    average = "평균",
    periodReturn = "기간 수익률",
    items = { count -> "${count}개 항목" },
    allWithCount = { count -> "전체 ($count)" },
    filteredAccounts = { selected, total, count -> "$total 중 ${selected}개 ($count)" },
    moreItems = { count -> "+${count}개 더보기" },
    sharesAt = { quantity, price -> "${quantity}주 @ $price" },
    deleteHoldingMessage = { symbol, quantity -> "$symbol (${quantity}주)을 삭제할까요?" },
    deleteCashMessage = { name -> "\"$name\"을 삭제할까요?" },
    editInAccount = { accountName -> "${accountName}에서 편집" },
    deleteFromAccount = { accountName -> "${accountName}에서 삭제" },
    targetMonthlySpendingLabel = { showInKrw -> "목표 월 지출 (${if (showInKrw) "KRW" else "USD"})" },
    recommendationShares = { current, target, currentShares, idealShares ->
        "$current% -> $target% ($currentShares -> ${"%.2f".format(idealShares)}주)"
    },
    sortOptionLabel = { option ->
        when (option) {
            SortOption.WEIGHT -> "비중"
            SortOption.NAME -> "이름"
            SortOption.SYMBOL -> "종목"
            SortOption.GAIN_LOSS_PERCENT -> "손익 %"
            SortOption.DAY_CHANGE_PERCENT -> "일일 변동 %"
        }
    }
)

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }
val LocalAppStrings = staticCompositionLocalOf { EnglishAppStrings }

@Composable
fun FolioLocalization(
    language: AppLanguage,
    content: @Composable () -> Unit
) {
    CompositionLocalProvider(
        LocalAppLanguage provides language,
        LocalAppStrings provides when (language) {
            AppLanguage.ENGLISH -> EnglishAppStrings
            AppLanguage.KOREAN -> KoreanAppStrings
        },
        content = content
    )
}
